### ISSUE TITLE
Consider adding an activity graph to the org README

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/.github#12]
Could use:

- https://github.com/herdstat

**Comment by chartgerink** [comment]
Do we still want something like this? I am happy to implement this for us - I always like these kinds of graphs 😊 

PS: I always found this incredibly cool as well - https://skyline.github.com/

**Comment by Bisaloo** [comment]
Yes, this issue is still relevant. I've tried to use herdstat but it doesn't seem to produce valid svg. Or the data is mangled. I'm not quite sure but it was producing visually empty activity graphs (the data in the svg source was still not 0 :shrug:). Feel free to give it a go.

**Comment by chartgerink** [comment]
I debugged a bit/too much and opened https://github.com/herdstat/herdstat/pull/64 to try and fix the underlying issue. 😊

**Comment by Bisaloo** [comment]
Fixed by https://github.com/epiverse-trace/.github/commit/5364398c3de56220ea331908c14e9db1ab6b538b. Thanks @chartgerink :pray:!
