### ISSUE TITLE
Directly include code of conduct

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/.github#26]
While reviewing this repo, I noticed [the code of conduct](https://github.com/epiverse-trace/.github/blob/main/CODE_OF_CONDUCT.md) links out to two Google Docs, which are not tracked in this repository directly.

Might it be an idea to directly include the code of conduct in the repo as a markdown file? I'd be happy to port it over if we want this. 

My arguments for moving it over:
- Reduce amounts of clicks needed to access the relevant content
- Version-control of document history (including revisions)
- It will be a great time to also review the contents as they're still denoting Anna and Claudine

Would be interested to hear your thoughts @Bisaloo.

**Comment by Bisaloo** [comment]
How do you propose we deal with the multilingual aspect if we go this route? One after the other in the same document? Main document still linking out but to two git-tracked md files?

**Comment by chartgerink** [comment]
Summarizing options for reference:
1. One big markdown file with both in the same doc (indicated by @Bisaloo)
2. `CODE_OF_CONDUCT` links to multiple markdown files in different languages (indicated by @Bisaloo)
3. One primary language `CODE_OF_CONDUCT` file, with links to different languages at the top

Option 2 is the smallest change from the current situation and the most flexible in case we want to add other languages. Also, the change history is least convoluted if we keep them in separate files. At this time, I think my vote would be for option two as you indicated.

**Comment by Bisaloo** [comment]
Yes, let's go with option 2 at this time please.
