### ISSUE TITLE
update community manager and email

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/.github#39]
Should we redirect to get in touch with us on the Discussions page?

https://github.com/epiverse-trace/.github/blob/95a73cc134dcf191f38686eb4335b785f67e2bed/CONTRIBUTING.md?plain=1#L1-L3

**Comment by Bisaloo** [comment]
Fixed by https://github.com/epiverse-trace/.github/commit/0c1d4f08b142792cc45f1c88dd6232f9a79e7f17 & https://github.com/epiverse-trace/.github/commit/a9b41793eb01157d2ec54157ad28cc7b8b613a8d
